#version 430 core

layout(binding = 0, rgba32f) uniform image2D framebuffer;

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

void main(void){
    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(framebuffer);
    if (pix.x >= size.x || pix.y >= size.y) {
        return;
    }
    vec4 color = vec4(gl_LocalInvocationID.xyz, 0);
    imageStore(framebuffer, pix, color);
}